feishu:
  # 该区域请于飞书开放平台查询本机器人信息,详见
  # https://open.feishu.cn/document/home/develop-a-bot-in-5-minutes/coding
  appId: cli_xxxxxxxxxxxxxxxx
  appSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  verificationToken: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  encryptKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  larkHost: "https://open.feishu.cn"

server:
  # 端口，请根据实际情况为准
  port: 3000

# add your custom fields here
token:
  spreadSheetToken: shtxxxxxxxxxxxxxxxxxxxxxxxx
  sheetId: xxxxxx
  approvalCode: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
